# Generated by Django 4.1.3 on 2023-06-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=150)),
                ("price", models.IntegerField()),
                ("image", models.TextField()),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("diesel", "Diesel"),
                            ("essence", "Essence"),
                            ("electrique", "Électrique"),
                        ],
                        max_length=50,
                    ),
                ),
                ("year", models.IntegerField()),
                ("description", models.TextField()),
                ("km", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
            ],
        ),
    ]
